CAPTIONS={
25:['Select the object you want to copy.','Right-click and choose Copy Objects.','Choose Paste Objects to add the copy.','Select an object and choose Delete to remove it.'],
28:['Select the objects to parent, with the intended parent selected last.','Open the object context menu and choose the parenting action.','Check the parent–child relationship in the Outliner.'],
29:['Start with the objects you want to organize.','Select the objects that belong together.','Open the object context menu.','Choose Move to Collection.','Choose an existing collection or create a new one.','Check the resulting collection in the Outliner.'],
32:['Faces form the surfaces.','Edges connect the vertices.','Vertices define points in space.'],
38:['Select the geometry you want to remove.','Open Delete and choose the element type.','Inspect the opening left by the deleted face.'],
40:['Choose the Extrude tool in Edit Mode.','Select the face to extrude.','Drag the tool handle to extend the face.'],
41:['Switch to Edit Mode.','Choose the Loop Cut tool.','Hover over an edge to preview the new loop.','Click to insert the loop.','Slide the loop into position and confirm.'],
42:['Choose the Inset tool.','Select the faces to inset.','Drag inward to create a border inside the selected faces.'],
43:['Switch to Edge Select mode.','Choose the Bevel tool.','Select the edges to bevel.','Drag to adjust the bevel width.'],
44:['Choose the Knife tool.','Click to define the cut, then confirm it.'],
49:['Visible edges, without shading.','Flat color, without visible edges.','Shading makes the form readable.'],
50:['Diffuse reflection scatters light.','Specular reflection creates visible reflections.']}
INSTRUCTIONS={
2:'Use the Viewport to work with objects, the Outliner to find them, Properties to edit settings, and the Timeline to manage time.',
3:'Start in Layout to arrange objects and review the scene.',4:'Use Modeling to edit object geometry.',5:'Use Sculpting to shape organic forms with brushes.',14:'Change an editor type to show the tools you need.',
16:'Identify the cube, camera, light, axes, and viewport controls.',17:'Use the viewport navigation controls to change your view.',18:'Practice orbiting, panning, and zooming with the mouse and keyboard.',19:'Frame the selected object to find it quickly.',
20:'Select the object you want to work with.',21:'Select or deselect all objects before applying an operation.',22:'Use the transform gizmos to move, rotate, or scale an object.',23:'Use the Transform properties for precise values.',24:'Add a primitive as the starting point for a new object.',25:'Copy, paste, or delete objects using the demonstrated commands.',26:'Compare flat and smooth shading on the same shape.',27:'Give objects clear names so they are easy to find.',28:'Parent objects to control them together.',29:'Use collections to organize related objects.',30:'Hide objects temporarily to make the scene easier to work with.',31:'Compare an independent duplicate with a linked duplicate.',
33:'Press Tab to switch between Object Mode and Edit Mode.',34:'In Edit Mode, use the number-row keys: 1 for vertices, 2 for edges, and 3 for faces.',35:'Select connected edges as a loop or ring.',36:'Select a connected loop of faces.',37:'Select a path between elements using Ctrl-click.',38:'Choose which geometry to delete.',39:'Compare the results of deleting vertices, edges, and faces.',40:'Extrude a selected face to extend the form.',41:'Add an edge loop, then position it.',42:'Inset a face to create an inner border.',43:'Bevel edges to soften corners.',44:'Cut new edges into the mesh.',45:'Select boundary vertices and press F to create a face.',46:'Merge selected vertices into one.',47:'Connect selected vertices with an edge.',48:'Subdivide the mesh to add geometry.',
54:'Create a material or remove a material assignment.',55:'Edit the material properties and inspect the result.',56:'Select faces in Edit Mode and assign a material to them.',57:'Enable Auto Keying to record supported changes at the current frame.',58:'Insert keyframes manually for the properties you want to animate.',59:'Set the frame rate before planning your animation timing.',60:'Move, duplicate, or delete keyframes to revise the animation.',61:'Animate a property by setting different values at different frames.',62:'Animation can affect lights, cameras, textures, particles, modifiers, and materials.',63:'Compare interpolation modes, then select the keyframes you want to change.',64:'Use a path to guide an object’s movement.',65:'Use Track To to point an object toward a target.'}
